name: Update RPZ Blocklists

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: '5.36'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential

      - name: Install cpanminus
        run: curl -L https://cpanmin.us | perl - App::cpanminus

      - name: Install Perl dependencies via cpanm
        run: |
          cpanm --notest LWP::UserAgent LWP::Protocol::https IO::Socket::SSL Text::CSV

      - name: Debug directory contents
        run: |
          echo "Listing contents of tools/ directory:"
          ls -la tools/
          echo "Checking if list-mappings.csv exists:"
          test -f tools/list-mappings.csv && echo "File exists" || echo "File does not exist"

      - name: Generate RPZ blocklists
        run: |
          mkdir -p tools/logs
          # Delete all existing .rpz files in category directories
          find ads/ malware/ phishing/ tracking/ misc/ -type f -name "*.rpz" -delete
          perl tools/blocklist2rpz-multi.pl -w -d ./ -l tools/urllist.txt -m tools/list-mappings.csv \
            -e tools/logs/error_$(date +%Y%m%d_%H%M%S).log \
            -s tools/logs/status_$(date +%Y%m%d_%H%M%S).txt \
            --validate --validation-report tools/logs/validation_$(date +%Y%m%d_%H%M%S).txt

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add ads/ malware/ phishing/ tracking/ misc/ tools/list-mappings.csv
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Automated update: RPZ blocklists ($(date -u))"
            git pull --rebase origin ${{ github.ref_name }}
            git push
          fi
