name: Update RPZ Blocklists

on:
  schedule:
    - cron: '0 * * * *'  # Runs hourly
  workflow_dispatch:  # Allows manual triggering

jobs:
  update-rpz:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full history for change detection

      - name: Restore source_metadata.json from artifact (if exists)
        uses: actions/download-artifact@v4
        with:
          name: rpz-logs
          path: tools/logs
        continue-on-error: true

      - name: Set up Perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: '5.36'

      - name: Install Perl dependencies
        run: |
          cpanm --notest LWP::UserAgent HTTP::Request URI::Escape JSON Text::CSV Digest::SHA File::Slurp
        env:
          PERL5LIB: ${{ github.workspace }}/local/lib/perl5:${{ github.workspace }}/local/lib/perl5/x86_64-linux

      - name: Create directories
        run: |
          mkdir -p ads malware phishing tracking misc social tools/logs

      - name: Run blocklist2rpz-multi.pl
        run: |
          cd "$GITHUB_WORKSPACE/tools"
          perl blocklist2rpz-multi.pl -w -d .. -l urllist.txt -m list-mappings.csv -e logs/error_$(date +%Y%m%d_%H%M%S).log -s logs/status_$(date +%Y%m%d_%H%M%S).txt --validate --validation-report logs/validation_$(date +%Y%m%d_%H%M%S).txt

      - name: Commit and push changes
        run: |
          cd "$GITHUB_WORKSPACE"
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add ads/*.rpz malware/*.rpz phishing/*.rpz tracking/*.rpz misc/*.rpz social/*.rpz SOURCES.md
          git diff --cached --ignore-matching-lines='^;.*\(.*\)$' --ignore-matching-lines='^;.*[0-9]\{8\}' > diff_output.txt
          if [ -s diff_output.txt ]; then
            git commit -m "Update RPZ blocklists and SOURCES.md"
            git push
          else
            echo "No significant changes to commit."
          fi

      - name: Upload logs
        uses: actions/upload-artifact@v4
        with:
          name: rpz-logs
          path: |
            tools/logs/*.log
            tools/logs/*.txt
            tools/logs/source_metadata.json
          retention-days: 7

      - name: Clean up old logs
        run: |
          find $GITHUB_WORKSPACE/tools/logs/ -type f -mtime +7 -delete
        if: always()
