name: Update RPZ Blocklists

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  update-rpz:
    runs-on: ubuntu-24.04

    env:
      RPZ_DIRS: ads malware phishing tracking misc social

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up Perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: '5.36'
          install-modules: |
            LWP::UserAgent
            LWP::Protocol::https
            IO::Socket::SSL
            Text::CSV
            JSON
            Digest::SHA
            File::Slurp

      - name: Cache Perl modules
        uses: actions/cache@v4
        with:
          path: |
            ~/perl5
            ${{ github.workspace }}/local/lib/perl5
            ${{ github.workspace }}/local/lib/perl5/x86_64-linux
          key: ${{ runner.os }}-cpan-${{ hashFiles('tools/urllist.txt', 'tools/list-mappings.csv') }}
          restore-keys: |
            ${{ runner.os }}-cpan-

      - name: Run blocklist2rpz-multi.pl
        run: |
          cd "$GITHUB_WORKSPACE"
          echo "Current directory: $(pwd)"
          echo "Workspace: $GITHUB_WORKSPACE"
          mkdir -p tools/logs
          echo "Logs directory content before run:"
          ls -la tools/logs
          TIMESTAMP=$(date +%Y%m%d_%H%M%S)
          echo "Will write to: tools/logs/error_${TIMESTAMP}.log"
          perl tools/blocklist2rpz-multi.pl \
            -w \
            -d . \
            -l tools/urllist.txt \
            -m tools/list-mappings.csv \
            -e tools/logs/error_${TIMESTAMP}.log \
            -s tools/logs/status_${TIMESTAMP}.txt \
            --validate \
            --validation-report tools/logs/validation_${TIMESTAMP}.txt

      - name: List logs directory
        run: |
          echo "Logs directory content before upload:"
          ls -la $GITHUB_WORKSPACE/tools/logs/

      - name: Upload logs as artifact
        uses: actions/upload-artifact@v4
        with:
          name: rpz-logs
          path: tools/logs/*.*
          retention-days: 7

      - name: Clean up old logs
        run: |
          find $GITHUB_WORKSPACE/tools/logs/ -type f -mtime +7 -delete

      - name: Commit and push changes
        run: |
          cd "$GITHUB_WORKSPACE"
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git add .
          # Check for changes excluding dynamic comments
          if git diff --staged --quiet -- '*.rpz' || \
             git diff --staged -- '*.rpz' | grep -vE '^(; Generated by|; Conversion date|; Number of entries)' | grep -q .; then
            git commit -m "Automated update: RPZ blocklists ($(date -u))" || echo "No changes to commit"
            git pull --rebase origin ${{ github.ref_name }}
            git push origin ${{ github.ref_name }}
          else
            echo "No meaningful changes to commit (only dynamic comments changed)."
            exit 0
          fi
