name: Update RPZ Blocklists

on:
  schedule:
    - cron: '0 * * * *' # Run hourly
  workflow_dispatch: # Allow manual trigger

env:
  RPZ_DIRS: ads malware phishing tracking misc # Add here new categories

jobs:
  update-rpz:
    runs-on: ubuntu-24.04
    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          token: ${{ secrets.GITHUB_TOKEN }}

      # Step 2: Set up Perl
      - name: Set up Perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: '5.36'
          install-modules: |
            LWP::UserAgent
            LWP::Protocol::https
            IO::Socket::SSL
            Text::CSV

      # Step 3: Cache CPAN modules
      - name: Cache CPAN modules
        uses: actions/cache@v4
        with:
          path: |
            ~/perl5
            /home/runner/work/RPZ-Blocklists/RPZ-Blocklists/local/lib/perl5
            /home/runner/work/RPZ-Blocklists/RPZ-Blocklists/local/lib/perl5/x86_64-linux
          key: ${{ runner.os }}-cpan-${{ hashFiles('tools/blocklist2rpz-multi.pl') }}
          restore-keys: |
            ${{ runner.os }}-cpan-

      # Step 4: Generate RPZ blocklists (with absolute paths and debug info)
      - name: Generate RPZ blocklists
        run: |
          echo "Current directory: $(pwd)"
          mkdir -p "$GITHUB_WORKSPACE/tools/logs"
          echo "Logs directory content:"
          ls -la "$GITHUB_WORKSPACE/tools/logs"
          TIMESTAMP=$(date +%Y%m%d_%H%M%S)
          perl "$GITHUB_WORKSPACE/tools/blocklist2rpz-multi.pl" \
            -w \
            -d "$GITHUB_WORKSPACE/" \
            -l "$GITHUB_WORKSPACE/tools/urllist.txt" \
            -m "$GITHUB_WORKSPACE/tools/list-mappings.csv" \
            -e "$GITHUB_WORKSPACE/tools/logs/error_${TIMESTAMP}.log" \
            -s "$GITHUB_WORKSPACE/tools/logs/status_${TIMESTAMP}.txt" \
            --validate \
            --validation-report "$GITHUB_WORKSPACE/tools/logs/validation_${TIMESTAMP}.txt"

      # Step 5: Upload logs as artifact
      - name: Upload logs
        uses: actions/upload-artifact@v4
        with:
          name: rpz-logs
          path: $GITHUB_WORKSPACE/tools/logs/
          retention-days: 7

      # Step 6: Commit and push changes
      - name: Commit and push changes
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Automated update: RPZ blocklists ($(date -u))" || echo "No changes to commit"
          git pull --rebase origin main
          git push origin main
