name: Update RPZ Blocklists

on:
  # Run this workflow every hour at minute 0 (i.e., at the start of each hour, UTC)
  schedule:
    - cron: '0 * * * *'
  # Allow manual triggering of the workflow from the GitHub UI
  workflow_dispatch:

env:
  # List of RPZ categories to process; add new categories here if needed
  RPZ_DIRS: "ads malware phishing tracking misc social"

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        # Check out the repository code so it can be used in the workflow
        uses: actions/checkout@v4

      - name: Setup Perl
        # Install the specified version of Perl using a GitHub Action
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: '5.36'

      - name: Install dependencies
        # Install required system and Perl dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential
          curl -L https://cpanmin.us | perl - App::cpanminus
          cpanm --notest LWP::UserAgent LWP::Protocol::https IO::Socket::SSL Text::CSV

      - name: Generate RPZ blocklists
        # Prepare log directories, clean up old RPZ files, and generate new blocklists
        run: |
          mkdir -p tools/logs
          chmod -R 777 tools/logs
          for dir in $RPZ_DIRS; do mkdir -p $dir; done
          find $RPZ_DIRS -type f -name "*.rpz" -delete
          perl tools/blocklist2rpz-multi.pl -w -d ./ -l tools/urllist.txt -m tools/list-mappings.csv \
            -e tools/logs/error_$(date +%Y%m%d_%H%M%S).log \
            -s tools/logs/status_$(date +%Y%m%d_%H%M%S).txt \
            --validate --validation-report tools/logs/validation_$(date +%Y%m%d_%H%M%S).txt

      - name: Debug log files
        # Output the contents of the log directory and log files for debugging
        run: |
          echo "Listing contents of tools/logs/:"
          ls -la tools/logs/ || echo "Directory tools/logs/ is empty or does not exist"
          echo "Status file contents:"
          cat tools/logs/status_*.txt || echo "No status file found"
          echo "Validation file contents:"
          cat tools/logs/validation_*.txt || echo "No validation file found"
          echo "Error file contents:"
          cat tools/logs/error_*.log || echo "No error file found"

      - name: Upload logs as artifact
        # Upload the log files as an artifact so they can be downloaded from the Actions UI
        uses: actions/upload-artifact@v4
        with:
          name: rpz-logs
          path: tools/logs/
          retention-days: 7

      - name: Commit and force-push changes
        # Commit any changes and force-push to the main branch if there are updates
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add $RPZ_DIRS tools/list-mappings.csv

          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Automated update: RPZ blocklists ($(date -u))"
            git fetch origin main
            git reset --hard origin/main
            git push --force-with-lease
          fi
