name: Update RPZ Blocklists

on:
  schedule:
    - cron: '0 12 * * *'  # Run daily at 12:00 UTC
  workflow_dispatch:  # Allow manual trigger

jobs:
  update-rpz:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch full history for git diff

      - name: Install BIND utilities
        run: sudo apt-get update && sudo apt-get install -y bind9-utils

      - name: Set up Perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: '5.36'

      - name: Install Perl dependencies
        run: |
          cpanm --notest LWP::UserAgent
          cpanm --notest HTTP::Request
          cpanm --notest URI::Escape
          cpanm --notest JSON

      - name: Create directories
        run: |
          mkdir -p ads malware phishing tracking misc social
          mkdir -p tools/logs

      - name: Generate RPZ blocklists
        run: |
          cd "$GITHUB_WORKSPACE/tools"
          perl blocklist2rpz-multi.pl -w -d .. -l urllist.txt -m list-mappings.csv -e logs/error_$(date +%Y%m%d_%H%M%S).log -s logs/status_$(date +%Y%m%d_%H%M%S).txt --validate --validation-report logs/validation_$(date +%Y%m%d_%H%M%S).txt

      - name: Validate RPZ files
        run: |
          cd "$GITHUB_WORKSPACE"
          find ads malware phishing tracking misc social -type f -name '*.rpz' | while read -r file; do
            echo "Validating $file"
            if ! named-checkzone -m 2048 -i none rpz.local "$file";
            if ! named-checkzone -i none rpz.local "$file"; then
              echo "Invalid RPZ file: $file"
              exit 1
            fi
          done

      - name: Commit and push changes
        run: |
          cd "$GITHUB_WORKSPACE"
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git add .
          # Check for changes excluding dynamic comments
          if ! git diff --staged --quiet -- '*.rpz'; then
              # Store diff output to avoid pipes
              changes=$(git diff --staged -- '*.rpz' | grep -vE '^(; Generated by|; Conversion date|; Number of entries)' || true)
              if [ -n "$changes" ]; then
                  git commit -m "Automated update: RPZ blocklists ($(date -u))" || echo "No changes to commit"
                  git pull --rebase origin ${{ github.ref_name }}
                  git push origin ${{ github.ref_name }}
              else
                  echo "No meaningful changes to commit (only dynamic comments changed)."
                  exit 0
              fi
          else
              echo "No changes in .rpz files."
              exit 0
          fi

      - name: Upload logs as artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: rpz-logs
          path: |
            tools/logs/*.log
            tools/logs/*.txt
            tools/source_metadata.json
          retention-days: 7
          if-no-files-found: warn
