name: Update RPZ Blocklists

on:
  schedule:
    - cron: '0 0 * * *' # Daily at midnight UTC
  workflow_dispatch: # Allow manual trigger

jobs:
  update-rpz:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch full history for git diff

      - name: Set up Perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: '5.36'

      - name: Install Perl dependencies
        run: |
          cpanm --notest LWP::UserAgent
          cpanm --notest HTTP::Request
          cpanm --notest URI::Escape
          cpanm --notest JSON

      - name: Create directories
        run: |
          mkdir -p ads malware phishing tracking misc social
          mkdir -p tools/logs

      - name: Run blocklist2rpz-multi.pl
        run: |
          cd "$GITHUB_WORKSPACE/tools"
          perl blocklist2rpz-multi.pl

      - name: Validate RPZ files
        run: |
          cd "$GITHUB_WORKSPACE"
          find ads malware phishing tracking misc social -type f -name '*.rpz' | while read -r file; do
            echo "Validating $file"
            if ! named-checkzone -i none rpz.local "$file"; then
              echo "Invalid RPZ file: $file"
              exit 1
            fi
          done

      - name: Generate SOURCES.md
        run: |
          cd "$GITHUB_WORKSPACE/tools"
          perl generate-sources-md.pl > ../SOURCES.md

      - name: Commit and push changes
        run: |
          cd "$GITHUB_WORKSPACE"
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git add .
          # Check for changes excluding dynamic comments
          if ! git diff --staged --quiet -- '*.rpz' || \
             git diff --staged -- '*.rpz' | grep -vE '^(; Generated by|; Conversion date|; Number of entries)' | grep -q . 2>/dev/null; then
            git commit -m "Automated update: RPZ blocklists ($(date -u))" || echo "No changes to commit"
            git pull --rebase origin ${{ github.ref_name }}
            git push origin ${{ github.ref_name }}
          else
            echo "No meaningful changes to commit (only dynamic comments changed)."
            exit 0
          fi

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: rpz-logs
          path: |
            tools/logs/*.log
            tools/logs/*.txt
            tools/source_metadata.json
          retention-days: 7
