name: Update RPZ Blocklists

on:
  schedule:
    - cron: '0 * * * *' # Run hourly
  workflow_dispatch: # Allow manual trigger

env:
  RPZ_DIRS: ads malware phishing tracking misc social # Add here new categories

jobs:
  update-rpz:
    runs-on: ubuntu-24.04
    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          token: ${{ secrets.GITHUB_TOKEN }}

      # Step 2: Set up Perl
      - name: Set up Perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: '5.36'
          install-modules: |
            LWP::UserAgent
            LWP::Protocol::https
            IO::Socket::SSL
            Text::CSV
            JSON
            XML::Simple

      # Step 3: Cache CPAN modules
      - name: Cache CPAN modules
        uses: actions/cache@v4
        with:
          path: |
            ~/perl5
            /home/runner/work/RPZ-Blocklists/RPZ-Blocklists/local/lib/perl5
            /home/runner/work/RPZ-Blocklists/RPZ-Blocklists/local/lib/perl5/x86_64-linux
          key: ${{ runner.os }}-cpan-${{ hashFiles('tools/blocklist2rpz-multi.pl', 'tools/urllist.txt', 'tools/list-mappings.csv') }}
          restore-keys: |
            ${{ runner.os }}-cpan-

      # Step 4: Generate RPZ blocklists
      - name: Generate RPZ blocklists
        run: |
          cd "$GITHUB_WORKSPACE"
          echo "Current directory: $(pwd)"
          echo "Workspace: $GITHUB_WORKSPACE"
          mkdir -p tools/logs
          echo "Logs directory content before run:"
          ls -la tools/logs
          TIMESTAMP=$(date +%Y%m%d_%H%M%S)
          echo "Will write to: tools/logs/error_${TIMESTAMP}.log"
          perl tools/blocklist2rpz-multi.pl \
            -w \
            -d . \
            -l tools/urllist.txt \
            -m tools/list-mappings.csv \
            -e tools/logs/error_${TIMESTAMP}.log \
            -s tools/logs/status_${TIMESTAMP}.txt \
            --validate \
            --validation-report tools/logs/validation_${TIMESTAMP}.txt

      # Step 5: Debug logs directory before upload
      - name: Debug logs directory before upload
        run: |
          echo "Logs directory content before upload:"
          ls -la $GITHUB_WORKSPACE/tools/logs/

      # Step 6: Upload logs as artifact
      - name: Upload logs
        uses: actions/upload-artifact@v4
        with:
          name: rpz-logs
          path: tools/logs/*.*
          retention-days: 7
          if-no-files-found: warn
          include-hidden-files: true

      # Step 7: Clean up old logs
      - name: Clean up old logs
        run: |
          find $GITHUB_WORKSPACE/tools/logs/ -type f -mtime +7 -delete
        if: always()

      # Step 8: Commit and push changes
      - name: Commit and push changes
        run: |
          cd "$GITHUB_WORKSPACE"
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Automated update: RPZ blocklists ($(date -u))" || echo "No changes to commit"
          git pull --rebase origin main
          git push origin main
